<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta http-equiv='Content-Type' content='text/html charset=UTF-8' />
    <title>Notificacion</title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
</head>
<body style='margin: 0 padding: 0'>
    <table align='center' border='0' cellpadding='0' cellspacing='0' width='600'>
        <tr>
            <td align='center' bgcolor='aliceblue' style='padding: 40px 0 30px 0'>
                <img src='http://www.sulferdust.com/images/email.png' alt='Creating Email Magic' width='300' height='230' style='display: block' />
            </td>
        </tr>
        <tr>
            <td bgcolor='#ffffff'>
                <table border='0' cellpadding='0' cellspacing='0' width='100%'>
                    <tr>
                        <td style='color: #153643; font-family: Arial, sans-serif; font-size: 24px; padding: 20px 30px 10px 30px;'>
                            <center>
                                <h3>Resolución recibida</h3>
                            </center>
                        </td>
                    </tr>
                    <tr>
                        <td> 
                           <p style='font-size: 20px;'>
                               ¡Hola! {{nombre_persona}}
                           </p>
                           <p style='font-size: 20px;'>
                               Usted a recibido la resolucion numero: {{numero}} del año: {{anio}}
                           </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor='#ee4c50'>
             <center style='padding: 10px 10px 10px 10px; color: white;'>
                 <h4>MESA DE PARTES 2019</h4>
             </center>
            </td>
        </tr>
    </table>
</body>
</html>