<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta http-equiv='Content-Type' content='text/html charset=UTF-8' />
    <title>Notificacion</title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
</head>
<body style='margin: 0 padding: 0'>
    <table align='center' border='0' cellpadding='0' cellspacing='0' width='600'>
        <tr>
            <td bgcolor='#27AE60'>
             <center style='padding: 0px 0px 0px 0px; color: white;'>
                 <h4>MESA DE PARTES 2019</h4>
             </center>
            </td>
        </tr>
       
        <tr>
            <td align='center' style='padding: 30px 0 30px 0;'>
                <img src='https://www.ugelchincha.gob.pe/wp-content/uploads/2016/11/logo.png' alt='Creating Email Magic' width='510' height='80' style='display: block' />
            </td>
        </tr>
    </table>

    <table align='center' border='0' cellpadding='0' cellspacing='0' width='600'>
        <tr>
            <td align='center' bgcolor='aliceblue' style='padding: 30px 0 30px 0'>
                <img src='http://www.sulferdust.com/images/email.png' alt='Creating Email Magic' width='250' height='180' style='display: block' />
            </td>
        </tr>
        <tr>
            <td bgcolor='#ffffff'>
                <table border='0' cellpadding='0' cellspacing='0' width='100%'>
                    <tr>
                        <td style='color: #153643; font-family: Arial, sans-serif; font-size: 24px; padding: 5px 30px 5px 30px;'>
                            <center>
                                <h3>¡Hola {{nombre}}!</h3>
                            </center>
                        </td>
                    </tr>                    
                    <tr>
                        <td> 
                           <p style='font-size: 20px;'>
                               Usted a recibido la siguiente resolución del área de Mesa de Parte - UGEL CHINCHA.
                           </p>
                        <table align='center' style='text-align: center; font-size: 20px;' border='1' cellpadding='0' cellspacing='0' width='600'>
                            <tr style='background: #AED6F1;'>
                                <td><strong>Tipo de resolución</strong></td>
                                <td><strong>Número</strong></td>
                                <td><strong>Año</strong></td>
                                <td><strong>Fecha de Emisión</strong></td>
                            </tr>
                            <tr style='background: #F2F3F4;'>
                                <td>{{tipo_resolucion}}</td>
                                <td>{{numero}}</td>
                                <td>{{anio}}</td>
                                <td>{{fecha_emision}}</td>
                            </tr>
                        </table>
                        <p style='font-size: 20px;'>
                              Atentamente: Christian Salazar Valdez
                        </p>
                </table>
            </td>
        </tr>

        <table align='center' border='0' cellpadding='0' cellspacing='0' width='600'>
        <tr>
            <td><br>
             <center style='padding: 0px 0px 0px 0px;'>
             	{{fecha}}
            </td>
        </tr>
        </table>
    </table>
    <table align='center' border='0' cellpadding='0' cellspacing='0' width='600'>
        <tr><br></br>
            <td bgcolor='#808B96'>
             <center style='padding: 0px 0px 0px 0px; color: white;'>
                 <h4>© 2018 - UGEL Chincha. Todos los derechos reservados | UGELCH 1.0 |</h4>
             </center>
            </td>
        </tr>
    </table>
</body>
</html>